// <auto-generated />
using System;
using Buildoc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Buildoc.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240919233931_NotBNullNovedadInspeccionFileModel")]
    partial class NotBNullNovedadInspeccionFileModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Buildoc.Models.FileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("IncidenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InspeccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NovedadInspeccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NovedadesIncidenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RespuestaInspeccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TipoInspeccionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncidenteId");

                    b.HasIndex("InspeccionId");

                    b.HasIndex("NovedadInspeccionId");

                    b.HasIndex("NovedadesIncidenteId");

                    b.HasIndex("RespuestaInspeccionId");

                    b.HasIndex("TipoInspeccionId");

                    b.ToTable("FileModels");
                });

            modelBuilder.Entity("Buildoc.Models.Incidente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CierrePorServidor")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateOnly>("FechaIncidente")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("HoraIncidente")
                        .HasColumnType("time");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sugerencia")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TipoIncidenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("TipoIncidenteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("Buildoc.Models.IncidenteLesionado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActividadRealizada")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AsociadaProyecto")
                        .HasColumnType("bit");

                    b.Property<bool>("Defuncion")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("GeneroAfectado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Hospitalizado")
                        .HasColumnType("bit");

                    b.Property<Guid>("IncidenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LesionadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PrimerosAuxilios")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IncidenteId");

                    b.HasIndex("LesionadoId");

                    b.ToTable("IncidenteLesionados");
                });

            modelBuilder.Entity("Buildoc.Models.Inspeccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("DuracionHoras")
                        .HasColumnType("int");

                    b.Property<bool>("EsTodoElDia")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInspeccion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaProgramacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspectorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RespuestaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoInspeccionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InspectorId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("TipoInspeccionId");

                    b.ToTable("Inspeccion");
                });

            modelBuilder.Entity("Buildoc.Models.Inspecciones.NovedadInspeccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InspeccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("InspeccionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("NovedadInspeccion");
                });

            modelBuilder.Entity("Buildoc.Models.Lesionado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long?>("Cedula")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<bool>("ConfimacionDefuncion")
                        .HasColumnType("bit");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Lesionados");
                });

            modelBuilder.Entity("Buildoc.Models.NovedadesIncidente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoNovedad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("IncidenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IncidenteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("NovedadesIncidentes");
                });

            modelBuilder.Entity("Buildoc.Models.Proyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CoordinadorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CoordinadorId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("Buildoc.Models.RespuestaInspeccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AccionesCorrectivas")
                        .HasColumnType("bit");

                    b.Property<string>("AccionesCorrectivasLista")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EsNecesariaInspeccionAdicional")
                        .HasColumnType("bit");

                    b.Property<int>("EstadoRespuestaInspeccion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEdicion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("InspeccionAdicionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InspeccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("RecomendacionesFuturas")
                        .HasColumnType("bit");

                    b.Property<string>("RecomendacionesFuturasList")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("InspeccionAdicionalId");

                    b.HasIndex("InspeccionId")
                        .IsUnique();

                    b.ToTable("RespuestaInspeccion");
                });

            modelBuilder.Entity("Buildoc.Models.TipoIncidente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Gravedad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("TipoIncidentes");
                });

            modelBuilder.Entity("Buildoc.Models.TipoInspeccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoInspeccion");
                });

            modelBuilder.Entity("Buildoc.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Arl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Cedula")
                        .HasColumnType("bigint");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Eps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Profesion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Telefono")
                        .HasColumnType("bigint");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProyectoUsuario", b =>
                {
                    b.Property<Guid>("ProyectosId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResidentesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProyectosId", "ResidentesId");

                    b.HasIndex("ResidentesId");

                    b.ToTable("ProyectoResidentes", (string)null);
                });

            modelBuilder.Entity("Buildoc.Models.FileModel", b =>
                {
                    b.HasOne("Buildoc.Models.Incidente", "Incidente")
                        .WithMany("FileModels")
                        .HasForeignKey("IncidenteId");

                    b.HasOne("Buildoc.Models.Inspeccion", "Inspeccion")
                        .WithMany("FileModels")
                        .HasForeignKey("InspeccionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Buildoc.Models.Inspecciones.NovedadInspeccion", "NovedadInspeccion")
                        .WithMany("FileModels")
                        .HasForeignKey("NovedadInspeccionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Buildoc.Models.NovedadesIncidente", "NovedadesIncidente")
                        .WithMany("FileModels")
                        .HasForeignKey("NovedadesIncidenteId");

                    b.HasOne("Buildoc.Models.RespuestaInspeccion", "RespuestaInspeccion")
                        .WithMany("FileModels")
                        .HasForeignKey("RespuestaInspeccionId");

                    b.HasOne("Buildoc.Models.TipoInspeccion", "TipoInspeccion")
                        .WithMany("Archivos")
                        .HasForeignKey("TipoInspeccionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Incidente");

                    b.Navigation("Inspeccion");

                    b.Navigation("NovedadInspeccion");

                    b.Navigation("NovedadesIncidente");

                    b.Navigation("RespuestaInspeccion");

                    b.Navigation("TipoInspeccion");
                });

            modelBuilder.Entity("Buildoc.Models.Incidente", b =>
                {
                    b.HasOne("Buildoc.Models.Proyecto", "Proyecto")
                        .WithMany("Incidentes")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buildoc.Models.TipoIncidente", "TipoIncidente")
                        .WithMany("Incidentes")
                        .HasForeignKey("TipoIncidenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Buildoc.Models.Usuario", "Usuario")
                        .WithMany("Incidentes")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Proyecto");

                    b.Navigation("TipoIncidente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Buildoc.Models.IncidenteLesionado", b =>
                {
                    b.HasOne("Buildoc.Models.Incidente", "Incidente")
                        .WithMany("IncidenteLesionados")
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buildoc.Models.Lesionado", "Lesionado")
                        .WithMany("IncidenteLesionados")
                        .HasForeignKey("LesionadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incidente");

                    b.Navigation("Lesionado");
                });

            modelBuilder.Entity("Buildoc.Models.Inspeccion", b =>
                {
                    b.HasOne("Buildoc.Models.Usuario", "Inspector")
                        .WithMany()
                        .HasForeignKey("InspectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buildoc.Models.Proyecto", "Proyecto")
                        .WithMany("Inspecciones")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buildoc.Models.TipoInspeccion", "TipoInspeccion")
                        .WithMany("Inspecciones")
                        .HasForeignKey("TipoInspeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspector");

                    b.Navigation("Proyecto");

                    b.Navigation("TipoInspeccion");
                });

            modelBuilder.Entity("Buildoc.Models.Inspecciones.NovedadInspeccion", b =>
                {
                    b.HasOne("Buildoc.Models.Inspeccion", "Inspeccion")
                        .WithMany("Novedades")
                        .HasForeignKey("InspeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buildoc.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Inspeccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Buildoc.Models.NovedadesIncidente", b =>
                {
                    b.HasOne("Buildoc.Models.Incidente", "Incidente")
                        .WithMany("NovedadesIncidentes")
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Buildoc.Models.Usuario", "Usuario")
                        .WithMany("NovedadesIncidentes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Incidente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Buildoc.Models.Proyecto", b =>
                {
                    b.HasOne("Buildoc.Models.Usuario", "Coordinador")
                        .WithMany()
                        .HasForeignKey("CoordinadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Coordinador");
                });

            modelBuilder.Entity("Buildoc.Models.RespuestaInspeccion", b =>
                {
                    b.HasOne("Buildoc.Models.Inspeccion", "InspeccionAdicional")
                        .WithMany()
                        .HasForeignKey("InspeccionAdicionalId");

                    b.HasOne("Buildoc.Models.Inspeccion", "Inspeccion")
                        .WithOne("Respuesta")
                        .HasForeignKey("Buildoc.Models.RespuestaInspeccion", "InspeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspeccion");

                    b.Navigation("InspeccionAdicional");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Buildoc.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Buildoc.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buildoc.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Buildoc.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoUsuario", b =>
                {
                    b.HasOne("Buildoc.Models.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buildoc.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ResidentesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Buildoc.Models.Incidente", b =>
                {
                    b.Navigation("FileModels");

                    b.Navigation("IncidenteLesionados");

                    b.Navigation("NovedadesIncidentes");
                });

            modelBuilder.Entity("Buildoc.Models.Inspeccion", b =>
                {
                    b.Navigation("FileModels");

                    b.Navigation("Novedades");

                    b.Navigation("Respuesta");
                });

            modelBuilder.Entity("Buildoc.Models.Inspecciones.NovedadInspeccion", b =>
                {
                    b.Navigation("FileModels");
                });

            modelBuilder.Entity("Buildoc.Models.Lesionado", b =>
                {
                    b.Navigation("IncidenteLesionados");
                });

            modelBuilder.Entity("Buildoc.Models.NovedadesIncidente", b =>
                {
                    b.Navigation("FileModels");
                });

            modelBuilder.Entity("Buildoc.Models.Proyecto", b =>
                {
                    b.Navigation("Incidentes");

                    b.Navigation("Inspecciones");
                });

            modelBuilder.Entity("Buildoc.Models.RespuestaInspeccion", b =>
                {
                    b.Navigation("FileModels");
                });

            modelBuilder.Entity("Buildoc.Models.TipoIncidente", b =>
                {
                    b.Navigation("Incidentes");
                });

            modelBuilder.Entity("Buildoc.Models.TipoInspeccion", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("Inspecciones");
                });

            modelBuilder.Entity("Buildoc.Models.Usuario", b =>
                {
                    b.Navigation("Incidentes");

                    b.Navigation("NovedadesIncidentes");
                });
#pragma warning restore 612, 618
        }
    }
}
